version: '2.17.2'
services:
  apiservice:
    build: ./api_service
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  request:
    build: ./request_service
    depends_on:
      - apiservice
    networks:
      - mynetwork
  
networks:
  mynetwork:
